spring:
  datasource:
    sql-script-encoding: utf-8
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/soloproject
    username: solo
    password: 1234

  jpa:
    database-platform=org:
      hibernate:
        dialect:
          PostgreSQLDialect:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
#    org.hibernate.SQL: DEBUG
    org.hibernate.type: trace
    org.springframework.secruity: DEBUG


server:
  port: 8085
