spring:
  datasource:
    sql-script-encoding: utf-8
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/soloProject
    username: solo
    password: 1234

  jpa:
    database-platform=org:
      hibernate:
        dialect:
          PostgreSQLDialect:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true

server:
  port: 8085
