spring:
  application:
    name: project-solo

  banner:
    location: banner/banner-${spring.profiles}.txt

  profiles:
    active: dev
    include:
      - datasource
      - logging


server:
  port: 8085

---
## 개발
spring:
  profiles: dev

